"""empty message

Revision ID: 504a8342f202
Revises: 6e1d7ead465d
Create Date: 2024-01-04 18:29:38.715236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504a8342f202'
down_revision = '6e1d7ead465d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=250),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=250),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
